-- E1-2: 사내 전자결재 + 휴가 신청 초기 스키마
-- 데이터 모델: docs/app/README.md 5절

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id      VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name          VARCHAR(100) NOT NULL,
    department    VARCHAR(100),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE user_roles (
    user_id BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role    VARCHAR(20) NOT NULL,   -- EMPLOYEE / APPROVER / ADMIN
    PRIMARY KEY (user_id, role)
);

CREATE TABLE documents (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type       VARCHAR(20)  NOT NULL,   -- APPROVAL / LEAVE
    title      VARCHAR(200) NOT NULL,
    body       TEXT,
    status     VARCHAR(20)  NOT NULL,   -- DRAFT / SUBMITTED / APPROVED / REJECTED
    drafter_id BIGINT       NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_documents_drafter ON documents(drafter_id);
CREATE INDEX idx_documents_status  ON documents(status);

CREATE TABLE leave_details (
    document_id BIGINT      PRIMARY KEY REFERENCES documents(id) ON DELETE CASCADE,
    leave_type  VARCHAR(20) NOT NULL,   -- ANNUAL / SICK / OTHER
    start_date  DATE        NOT NULL,
    end_date    DATE        NOT NULL,
    days        NUMERIC(4,1) NOT NULL
);

CREATE TABLE approval_lines (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT      NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    step        INT         NOT NULL,
    approver_id BIGINT      NOT NULL REFERENCES users(id),
    status      VARCHAR(20) NOT NULL,   -- PENDING / APPROVED / REJECTED
    acted_at    TIMESTAMPTZ,
    UNIQUE (document_id, step)
);
CREATE INDEX idx_approval_lines_approver ON approval_lines(approver_id);

-- 결재 이력 해시 체인 (전역 단일 체인, INSERT만 허용)
CREATE TABLE approval_history (
    seq         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT      NOT NULL REFERENCES documents(id),
    actor_id    BIGINT      NOT NULL REFERENCES users(id),
    action      VARCHAR(20) NOT NULL,   -- SUBMIT / APPROVE / REJECT
    acted_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    prev_hash   CHAR(64)    NOT NULL,
    hash        CHAR(64)    NOT NULL UNIQUE
);
CREATE INDEX idx_approval_history_document ON approval_history(document_id);

CREATE TABLE attachments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id  BIGINT       NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    object_key   VARCHAR(400) NOT NULL,
    file_name    VARCHAR(255) NOT NULL,
    content_type VARCHAR(100),
    size         BIGINT       NOT NULL,
    sha256       CHAR(64)     NOT NULL,
    uploaded_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_attachments_document ON attachments(document_id);

-- 백업 직전에 기록하는 체인 헤드 (불변 백업 매니페스트에 함께 올림)
CREATE TABLE chain_checkpoints (
    seq        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    head_hash  CHAR(64)    NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
